import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Budget Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          {/* Header */}
          <Header />
          <main className="min-h-screen">{children}</main>

          {/* Footer */}
          <footer className="bg-gray-400 py-5">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>Made by Lakshitha Vimuth © 2024</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
